### ISSUE TITLE
Exit 80131506 after installing Datadog csharp

### ISSUE THREAD

**Issue by nbosscher** [DataDog/dd-trace-csharp#216] opened 2018-11-16 17:43 UTC
**Describe the bug**
After installing Datadog c-sharp some of my applications won't start up, giving exit code `80131506`

**To Reproduce**
1. Install DataDog tracer from https://github.com/DataDog/dd-trace-csharp/releases
2. Restart IIS using steps on https://docs.datadoghq.com/tracing/setup/dotnet/
3. Load application
4. App Pool crashes before first page is loaded

**Expected behavior**
The application works the same after installing Datadog tracer.

**Screenshots**
None

**Runtime environment (please complete the following information):**
- Instrumentation mode: automatic with msi installer
- Tracer version: 0.5.0
- OS: Windows Server 2016 Data Center
- CLR: .NET 4.0.30319 (reported in IIS), .NET 4.7 installed on machine

**Additional context**
Event Viewer Logs
```
Application Error:
Faulting application name: w3wp.exe, version: 10.0.14393.0, time stamp: 0x57899b8a
Faulting module name: clr.dll, version: 4.7.3190.0, time stamp: 0x5b693b48
Exception code: 0xc0000005
Fault offset: 0x000000000056604b
Faulting process id: 0x4d8
Faulting application start time: 0x01d47a9f85863416
Faulting application path: c:\windows\system32\inetsrv\w3wp.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Report Id: 769c85ef-ad3c-45f2-9441-e4d4ce2a7381
Faulting package full name: 
Faulting package-relative application ID: 

.NET Runtime:
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an internal error in the .NET Runtime at IP 00007FFD0A77604B (00007FFD0A210000) with exit code 80131506.
```

Attempted to change GC settings, but it didn't help
- tried `<gcServer enabled="true" />`
- tried `<gcConcurrent enabled="false" />`

Oddly this doesn't happen for all of my .NET applications, some work fine.
- both applications are compiled with `.NET 4.5.2`

Checked `ProgramData\Datadog .NET Tracer\logs\dotnet-profiler.log`, but it only had `[info]` level messages in it

I was able to attach are remote debugger to the failing process and received the following stack trace:
```
"Access Violation"
clr.dll!ProfToEEInterfaceImpl::GetModuleFlags(class Module *)
clr.dll!ProfToEEInterfaceImpl::GetModuleInfo2(unsigned __int64,unsigned char const * *,unsigned long,unsigned long *,unsigned short * const,unsigned __int64 *,unsigned long *)
Datadog.Trace.ClrProfiler.Native.dll!00007ffcd9ec1bee()
```

I was able to narrow down the culprit to applications that had ClearScript as a dependancy. After removing ClearScript, those applications ran without error when Datadog .NET was installed.

While I was able to do a bunch of work to my application to remove ClearScript, it looks like Datadog is mishandling dependancies in certain scenarios. It's calling clr.dll/GetModuleInfo2() with an invalid module id.

**Comment by lucaspimentel** [comment] 2018-11-16 22:38
Closing this as a duplicate of #207. Sorry about the confusing, that was my fault.

**Closed by lucaspimentel** 2018-11-16 22:38 UTC
Labels: bug
