### ISSUE TITLE
Could not load file or assembly System.CodeDom

### ISSUE THREAD

**Issue by swASO** [DataDog/dd-trace-csharp#186] opened 2018-10-31 08:53 UTC
**Describe the bug**
I Updated from 0.3.1-beta to 0.5-beta and we got a exception in all our services ( linux/windows ) 

```
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at flowfact.services.attributes.ServiceRegister.<>c__DisplayClass3_0.<FindTypesByAttribute>b__1(Assembly s)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator2.ToList()
   at flowfact.services.attributes.ServiceRegister.FindTypesByAttribute(Type[] types)
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
System.IO.FileNotFoundException: Could not load file or assembly 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.CodeDom, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
```
 
**Runtime environment (please complete the following information):**
- Instrumentation mode: manual
- Tracer version: 0.5.0-beta
- OS: Linux / Docker image ( microsoft/dotnet:2.1-runtime-deps-stretch-slim )
- CLR: .Net Core 2.1

**Additional context**
i dont know what the exact problem is, but i think this lines below does produce the error 
with 0.3.1-beta everythings works fine ( already did the downgrade ), with 0.5-beta i can reproduce the exception above

```
private static List<(Type Type, object[] CustomAttributes)> FindTypesByAttribute(params Type[] types)
{
    try
    {
        var allTypes = AppDomain.CurrentDomain.GetAssemblies()
            .Where(s => !s.FullName.StartsWith("Microsoft") && !s.FullName.StartsWith("System."))
            .Select(s => s.GetTypes()
                .Select(type => (Type: type, CustomAttributes: type.GetCustomAttributes(true)))
                .Where(z => z.CustomAttributes.Length > 0 && z.CustomAttributes.Any(t => types.Any(i => i == t.GetType())))
            );

        return allTypes.SelectMany(s => s).ToList();
    }
    catch (Exception ex)
    {
        Logger.Error(ex);
    }
    return null;
}
```

**Comment by lucaspimentel** [comment] 2018-10-31 16:12
Thanks for reporting this, @swASO. To narrow down the issue to a specific release, can you test with [release 0.4.1](https://github.com/DataDog/dd-trace-csharp/releases/tag/v0.4.1-beta)? That was the last release before 0.5.0.

**Comment by swASO** [comment] 2018-10-31 16:33
v0.5.0 -> :-1: 
v0.4.1 -> :-1: 
v0.4.0 -> :-1: 
v0.3.2 -> :+1:  
v0.3.1 -> :+1:

**Comment by lucaspimentel** [comment] 2018-11-01 13:01
@swASO: Thanks for the code sample. We were able to reproduce the issue.

**Comment by lucaspimentel** [comment] 2018-11-01 13:36
It looks like the error is caused by a `MsgPack.Cli` dependency. In [v0.4.0](https://github.com/DataDog/dd-trace-csharp/releases/tag/v0.4.0-beta), we updated the `MsgPack.Cli` NuGet reference from 0.9.2 to 1.0.0 (see #158). `MsgPack.Cli` has [a reference to `System.CodeDom` 4.4.0](https://github.com/msgpack/msgpack-cli/blob/ead1f728291d922beaf7a2a1bbb2fe7f6c166bf9/src/MsgPack/MsgPack.csproj#L60) which is not included in the [nuspec file](https://github.com/msgpack/msgpack-cli/blob/1.0.0/MsgPack.nuspec), so it doesn't show up in their [NuGet package](https://www.nuget.org/packages/MsgPack.Cli/1.0.0).

[This issue in their repo](https://github.com/msgpack/msgpack-cli/issues/283) seems to be related.

In the short term, you can avoid the exception by skipping the MsgPack assembly in the LINQ query:

```csharp
var allTypes = AppDomain.CurrentDomain
                        .GetAssemblies()
                        .Where(s => !s.FullName.StartsWith("Microsoft") &&
                                    !s.FullName.StartsWith("System.") &&
                                    !s.FullName.StartsWith("MsgPack"))   // skip MsgPack
                        .Select(s => s.GetTypes()
```

**Comment by lucaspimentel** [comment] 2018-11-01 13:58
You can repro the issue with a single line of code and no reference to Datadog assemblies:

```csharp
Type[] types = typeof(MsgPack.AsyncReadResult).Assembly.GetTypes();
```

**Comment by lucaspimentel** [comment] 2018-11-01 16:33
I created [this PR](https://github.com/msgpack/msgpack-cli/pull/306) so it can be fixed in the next release of their library.

**Comment by swASO** [comment] 2018-11-02 08:42
workaround works! thanks

**Comment by lucaspimentel** [comment] 2018-11-07 22:06
I'm closing this since there is nothing else for us to do.

**Closed by lucaspimentel** 2018-11-07 22:06 UTC
Labels: core
